services:
  hackcable:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run dev
    environment:
      CHOKIDAR_USEPOLLING: "true"
      WATCHPACK_POLLING: "true"
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
